version: '2'
services:
  topics_api:
    image: composer/composer
    volumes:
      - ./topics/api:/app
    command:
      - update
  topics_bushtaxi:
    image: dockmoe/php:7-cli
    volumes:
      - ./topics/bushtaxi:/app
    working_dir:
        /app
    command:
      - composer
      - update
  votes_api:
    image: dockmoe/php:7-cli
    volumes:
      - ./votes/api:/app
    working_dir: /app
    command:
      - composer
      - update
  votes_bushtaxi:
    image: dockmoe/php:7-cli
    volumes:
      - ./votes/bushtaxi:/app
    working_dir: /app
    command:
      - composer
      - update
