version: '2'
services:
  api:
    image: composer/composer
    volumes:
      - ./api:/app
    ports:
      - 8888:80
    command:
      - run-script
      - --timeout=0
      - run
  www:
    image: nginx
    volumes:
      - ./www:/usr/share/nginx/html:ro
    ports:
      - 80:80
